version: '3'

services:
  blog:
    image: ${DOCKER_USERNAME}/my-personal-blog:latest
    container_name: my-personal-blog
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - /data/resume:/usr/share/nginx/html/resume:ro
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
